-- Phase 4: destinations and versioning. Engine destinations (restic, rclone) on local, SFTP,
-- S3-compatible and Backblaze B2 targets; encryption custody and the recovery kit; bandwidth
-- limits and transfer windows; restic snapshots and forget requests; deferred jobs. Times are
-- RFC3339 UTC text (db.TimeFormat); JSON columns are text. Contract: docs/design/phase4.md,
-- revision 2 (§13.1 lists what changes and why). Unreleased: this file may still change until
-- Phase 4 ships. The engine binaries' paths are bootstrap environment variables
-- (BUNKARR_RESTIC_PATH, BUNKARR_RCLONE_PATH), never settings rows: whoever chooses the program
-- receives every destination's secrets (phase4.md §4.4).
--
-- Only additive changes: new columns with defaults (ALTER TABLE ADD COLUMN; a CHECK on an added
-- column is tested against the existing rows, which the defaults satisfy) and new tables. No table
-- is rebuilt, so the upgrade copies no job history. Every Phase 1-3 destination is filecopy on a
-- local or mounted path and keeps its meaning: kind 'local', remote '{}', encryption 'none'.
--
-- Columns that 0002 already reserved for Phase 4 and that this phase starts to use:
--   destinations.engine       'restic' and 'rclone' (the CHECK already allows them);
--   destinations.credentials  sealed JSON with AAD "destination:<id>:credentials": the storage
--                             credentials only (SFTP key or password, S3 or B2 keys), which may be
--                             rotated; the encryption secret has its own column below (§4.3);
--   destinations.bandwidth    {uploadKiBps, downloadKiBps, timetable:[...], window:{...}} (§9.1);
--   destinations.marker_id    restic: "restic:<repository id>" (S25); rclone: the uuid of the
--                             remote's .bunkarr/destination.json; filecopy: as in Phase 1;
--                             "pending:<uuid>" while a create has not finished (the row is inserted
--                             before restic init so a generated secret is never lost; a pending
--                             marker matches no repository, so no job runs, §4.5);
--   destinations.target       remote kinds: the display location (sftp://user@host:port/path,
--                             s3:<endpoint>/<bucket>/<prefix>, b2:<bucket>/<prefix>);
--   destinations.fs_type      remote kinds: the kind ('sftp', 's3', 'b2'); root_dev 0.

-- destinations -----------------------------------------------------------------------------------

-- The UI type (phase4.md §4.1): local (a path in the container: a filecopy destination or a restic
-- repository), sftp, s3 (S3-compatible) or b2 (Backblaze B2). Immutable, like engine and target.
ALTER TABLE destinations ADD COLUMN kind TEXT NOT NULL DEFAULT 'local' CHECK (kind IN ('local', 'sftp', 's3', 'b2'));
-- Non-secret connection settings of a remote kind (§4.2), normalized JSON: sftp {host, port, user,
-- path, hostKeys: [{type, key}]} (each key parsed before it is stored); s3 {provider, endpoint,
-- region, bucket, prefix, storageClass, forcePathStyle, caCert}; b2 {bucket, prefix}; '{}' for
-- local. Decoded strictly (unknown fields refused); no field ever becomes an rclone option by
-- itself (§4.4). Only sftp hostKeys and s3 caCert may change after creation.
ALTER TABLE destinations ADD COLUMN remote TEXT NOT NULL DEFAULT '{}';
-- none: plain files (filecopy; rclone only with acceptUnencrypted); restic: the repository's own
-- encryption; crypt: an rclone crypt remote over the whole destination root (§5.1). Immutable.
ALTER TABLE destinations ADD COLUMN encryption TEXT NOT NULL DEFAULT 'none' CHECK (encryption IN ('none', 'restic', 'crypt'));
-- The encryption secret (restic password, or crypt password and password2), sealed JSON with AAD
-- "destination:<id>:encryptionSecret" (ADR 0003). Written once by Create and never by Update, so a
-- rotation of the storage credentials can never drop it (S21, §4.3). NULL: no secret (filecopy,
-- plain rclone).
ALTER TABLE destinations ADD COLUMN encryption_secret TEXT;
-- Who chose the encryption secret: generated by Bunkarr or supplied by the user. NULL: no secret.
ALTER TABLE destinations ADD COLUMN secret_origin TEXT CHECK (secret_origin IS NULL OR secret_origin IN ('generated', 'user'));
-- The recovery kit (§5.2): its last export, and the confirmation of custody. No job but a dry run
-- runs before kit_confirmed_at is set (S21): a generated secret is confirmed by the kit's check
-- code, a secret the user typed at create by typing it again; only attach is confirmed at creation.
ALTER TABLE destinations ADD COLUMN kit_exported_at TEXT;
ALTER TABLE destinations ADD COLUMN kit_confirmed_at TEXT;
-- restic destinations: 16 random bytes in hex, generated at create and attach and never changed
-- (D32). Every snapshot carries the tag bunkarr-dest:<engine_tag>, snapshot groups are
-- (engine_tag, kind, source or integration id), and every tag filter includes it. Row ids restart
-- in a new database and repeat after a delete and re-attach, so an earlier install's snapshots, a
-- re-created destination's and another Bunkarr's in the same repository belong to other tags and
-- are never forgotten (S24). NULL on filecopy and rclone destinations. (UNIQUE cannot be added by
-- ALTER TABLE; the partial index below enforces it.)
ALTER TABLE destinations ADD COLUMN engine_tag TEXT CHECK (engine_tag IS NULL OR (length(engine_tag) = 32 AND engine_tag NOT GLOB '*[^0-9a-f]*'));

CREATE UNIQUE INDEX destinations_engine_tag ON destinations (engine_tag) WHERE engine_tag IS NOT NULL;

-- destination_files (owned by internal/syncer) ---------------------------------------------------

-- restic destinations (§6.2, §6.3, D31). NULL on a live row: the recorded version (path, size,
-- mtime) is in the source's base, its newest snapshot recorded in engine_snapshots; the batch that
-- makes a new base re-checks every live row against that snapshot's content listing (restic ls) in
-- the same transaction. Set: a snapshot that the read-back showed to hold the recorded version (a
-- retained row's version, an update's old version kept as a 'replaced' row, or a live row whose
-- version the newer snapshots lack: held, failed, vanished or changed after the scan). A live
-- row's reference is only ever set from NULL to the previous base, or cleared when a new snapshot
-- holds the version; it is never moved to another snapshot, and a retained row's never changes.
-- Retention never forgets a snapshot a row references (S5, S24). NULL on filecopy and rclone rows.
ALTER TABLE destination_files ADD COLUMN engine_ref TEXT;
-- restic and rclone destinations: "headtail-sha256:<hex>" (filecopy.HeadTailHash) of the source
-- content that was backed up, read through the source's root just before the upload (§6.2, §7.3).
-- The move pairing (phase1.md §4.2) compares it instead of reading the stored copy, which would
-- download it. NULL on filecopy rows (the planner reads the destination file there); on an engine
-- row a NULL makes a rename a copy + retain.
ALTER TABLE destination_files ADD COLUMN head_tail TEXT;

CREATE INDEX destination_files_engine_ref ON destination_files (destination_id, engine_ref) WHERE engine_ref IS NOT NULL;

-- Config versions on engine destinations ----------------------------------------------------------

-- The restic snapshot (full id) holding a Plex DB or *arr version (snapshots, internal/snapshots)
-- or a manifest version (manifests, internal/manifest) on a restic destination (§8.2). The logical
-- version path (.bunkarr/<kind>/<folder>/<version>) stays in engine_snapshot_id / path, so the
-- uniqueness rules are those of Phases 1-3. NULL on filecopy and rclone destinations.
ALTER TABLE snapshots ADD COLUMN engine_ref TEXT;
ALTER TABLE manifests ADD COLUMN engine_ref TEXT;

-- jobs (owned by internal/jobqueue) ---------------------------------------------------------------

-- A queued job deferred by its runner (jobs.DeferredError: a transfer window closed) starts again
-- no earlier than not_before; deferrals counts the deferrals (§9.2, §11.2). A sync that superseded
-- deferred syncs continues their count (the windows the seed waited in a row).
ALTER TABLE jobs ADD COLUMN not_before TEXT;
ALTER TABLE jobs ADD COLUMN deferrals INTEGER NOT NULL DEFAULT 0;

CREATE INDEX jobs_not_before ON jobs (not_before) WHERE status = 'queued' AND not_before IS NOT NULL;

-- A deferred sync superseded by its schedule's next fire (§9.2) names the sync that replaced it
-- (the newest, when that one was superseded in turn): the new plan carries the window cuts of its
-- pending items, so the two-window backstop still ends a file that never fits.
ALTER TABLE jobs ADD COLUMN superseded_by INTEGER;

CREATE INDEX jobs_superseded_by ON jobs (superseded_by) WHERE superseded_by IS NOT NULL;

-- The pending items that a window's end cut (detail.windowCuts > 0): the only rows the carry reads.
-- A seed superseded day after day leaves a chain of cancelled syncs with many pending items each,
-- and the carry runs for every plan page inside the write transaction, so it must not scan them
-- (TestCarryCutsQueryUsesTheCutIndex). json_valid comes first: a detail that is not JSON is
-- skipped, never an error of the insert.
CREATE INDEX job_items_window_cuts ON job_items (job_id, status, json_extract(detail, '$.windowCuts'))
    WHERE status = 'pending' AND json_valid(detail) AND json_extract(detail, '$.windowCuts') > 0;

-- restic snapshots of sources (owned by internal/enginerun) -----------------------------------------

-- One row per snapshot a sync made at a restic destination: one per source and batch (§6.2),
-- inserted only after the snapshot's tags and content were read back, in the transaction that
-- records the batch. The newest row of a source is its base (§6.2), which retention always keeps.
-- Config versions are recorded in snapshots / manifests instead. A row is deleted when retention
-- forgot the snapshot, or when the preflight finds it removed outside Bunkarr. A source deleted in
-- Bunkarr leaves its snapshots as an orphan group of this destination's engine_tag (source_id
-- NULL), which retention never forgets (S24); snapshots with another engine_tag are never recorded
-- here and never forgotten.
CREATE TABLE engine_snapshots (
    id             INTEGER PRIMARY KEY,
    destination_id INTEGER NOT NULL REFERENCES destinations (id) ON DELETE CASCADE,
    source_id      INTEGER REFERENCES sources (id) ON DELETE SET NULL,
    job_id         INTEGER REFERENCES jobs (id) ON DELETE SET NULL,
    -- the full (64 hex) restic snapshot id
    snapshot_id    TEXT    NOT NULL,
    -- the snapshot's time (restic's "time")
    created_at     TEXT    NOT NULL,
    -- the batch of its job (1..n); complete = 1 on the last batch of a job, whose snapshot holds
    -- the whole plan (retention's daily/weekly/monthly/yearly buckets count complete snapshots only)
    batch          INTEGER NOT NULL DEFAULT 1,
    complete       INTEGER NOT NULL DEFAULT 0 CHECK (complete IN (0, 1)),
    -- from restic's summary line: total_files_processed, total_bytes_processed, data_added
    files          INTEGER NOT NULL DEFAULT 0,
    bytes          INTEGER NOT NULL DEFAULT 0,
    data_added     INTEGER NOT NULL DEFAULT 0,
    -- the whole summary line plus the tags and paths count, for diagnostics
    summary        TEXT    NOT NULL DEFAULT '{}',
    UNIQUE (destination_id, snapshot_id)
) STRICT;

CREATE INDEX engine_snapshots_source ON engine_snapshots (destination_id, source_id, created_at);
CREATE INDEX engine_snapshots_job ON engine_snapshots (job_id) WHERE job_id IS NOT NULL;

-- Snapshots to forget at a restic destination (owned by internal/enginerun). A Plex DB, *arr or
-- manifest runner that prunes a version on a restic destination deletes the version's row and
-- inserts this request in one transaction; the destination's next retention job forgets the snapshot
-- after the S24 checks and deletes the request (D28: forget needs restic's exclusive lock, which only
-- the retention job, serialized with syncs by the dest:<id> key, takes).
CREATE TABLE engine_forget (
    destination_id INTEGER NOT NULL REFERENCES destinations (id) ON DELETE CASCADE,
    snapshot_id    TEXT    NOT NULL,
    kind           TEXT    NOT NULL CHECK (kind IN ('plexdb', 'arr', 'manifest')),
    reason         TEXT    NOT NULL,
    requested_at   TEXT    NOT NULL,
    PRIMARY KEY (destination_id, snapshot_id)
) STRICT;

-- Per-destination engine state (owned by internal/enginerun).
CREATE TABLE engine_state (
    destination_id   INTEGER PRIMARY KEY REFERENCES destinations (id) ON DELETE CASCADE,
    -- the engine binary's version at the last job ("restic 0.18.1", "rclone v1.74.1")
    engine_version   TEXT    NOT NULL DEFAULT '',
    -- restic: the last successful prune (pruneEveryDays counts from it) and check
    last_prune_at    TEXT,
    last_check_at    TEXT,
    -- restic: n of the next "check --read-data-subset=n/t" (rotates 1..t, §6.6)
    read_subset_next INTEGER NOT NULL DEFAULT 1,
    -- rclone: the last "backend cleanup" of unfinished multipart uploads (§7.5)
    last_cleanup_at  TEXT,
    -- upload throughput measured by recent syncs (bytes/s, EWMA): the window fitting (§9.2)
    throughput_bps   REAL,
    -- repository or remote figures from the last check, prune or listing, for the UI
    stats            TEXT    NOT NULL DEFAULT '{}',
    updated_at       TEXT    NOT NULL
) STRICT;
